<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VisitorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('log_statistics')->insert(
            [
                [
                    'log_statistic_id'        => '1',
                    'ip_address'               => '192.168.43.1',
                    'url_access'              => 'fe.sttbandung.ac.id/fasilitas-dan-layanan',
                    'page_access'             => 'tentang-sttb/fasilitas-dan-layanan',
                    'hits_url_access'         => 9,
                    'browser_access'          => 'mozilla',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-01',
                ],

                [
                    'log_statistic_id'        => '2',
                    'ip_address'               => '192.168.43.2',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 4,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 7',
                    'created_at'              => '2022-01-02',
                ],

                [
                    'log_statistic_id'        => '3',
                    'ip_address'               => '192.168.43.3',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-03',
                ],

                [
                    'log_statistic_id'        => '4',
                    'ip_address'               => '192.168.43.4',
                    'url_access'              => 'fe.sttbandung.ac.id/galeri-wisuda',
                    'page_access'             => 'mahasiswa/galeri-wisuda',
                    'hits_url_access'         => 5,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-04',
                ],

                [
                    'log_statistic_id'        => '5',
                    'ip_address'               => '192.168.43.5',
                    'url_access'              => 'fe.sttbandung.ac.id/kerjasama',
                    'page_access'             => 'tentang-sttb/kerjasama',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-05',
                ],

                [
                    'log_statistic_id'        => '6',
                    'ip_address'               => '192.168.43.6',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/lomba-di-dubai',
                    'page_access'             => 'tentang-sttb/berita/lomba-di-dubai',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-06',
                ],

                [
                    'log_statistic_id'        => '7',
                    'ip_address'               => '192.168.43.7',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/kerja-di-jepang',
                    'page_access'             => 'tentang-sttb/berita/kerja-di-jepang',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-07',
                ],

                [
                    'log_statistic_id'        => '8',
                    'ip_address'               => '192.168.43.8',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/dosen',
                    'page_access'             => 'tentang-sttb/berita/dosen',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-08',
                ],

                [
                    'log_statistic_id'        => '9',
                    'ip_address'               => '192.168.43.9',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/paduan-suara-sttb',
                    'page_access'             => 'tentang-sttb/berita/paduan-suara-sttb',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-09',
                ],

                [
                    'log_statistic_id'        => '10',
                    'ip_address'               => '192.168.43.10',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/himatif',
                    'page_access'             => 'tentang-sttb/berita/himatif',
                    'hits_url_access'         => 10,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-09',
                ],

                [
                    'log_statistic_id'        => '11',
                    'ip_address'               => '192.168.43.11',
                    'url_access'              => 'fe.sttbandung.ac.id/fasilitas-dan-layanan',
                    'page_access'             => 'tentang-sttb/fasilitas-dan-layanan',
                    'hits_url_access'         => 9,
                    'browser_access'          => 'mozilla',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-01',
                ],

                [
                    'log_statistic_id'        => '12',
                    'ip_address'               => '192.168.43.12',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 4,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 7',
                    'created_at'              => '2022-01-02',
                ],

                [
                    'log_statistic_id'        => '13',
                    'ip_address'               => '192.168.43.13',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-03',
                ],

                [
                    'log_statistic_id'        => '14',
                    'ip_address'               => '192.168.43.14',
                    'url_access'              => 'fe.sttbandung.ac.id/galeri-wisuda',
                    'page_access'             => 'mahasiswa/galeri-wisuda',
                    'hits_url_access'         => 5,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-04',
                ],

                [
                    'log_statistic_id'        => '15',
                    'ip_address'               => '192.168.43.15',
                    'url_access'              => 'fe.sttbandung.ac.id/kerjasama',
                    'page_access'             => 'tentang-sttb/kerjasama',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-05',
                ],

                [
                    'log_statistic_id'        => '16',
                    'ip_address'               => '192.168.43.16',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/lomba-di-dubai',
                    'page_access'             => 'tentang-sttb/berita/lomba-di-dubai',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-06',
                ],

                [
                    'log_statistic_id'        => '17',
                    'ip_address'               => '192.168.43.17',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/kerja-di-jepang',
                    'page_access'             => 'tentang-sttb/berita/kerja-di-jepang',
                    'hits_url_access'         => 4,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-07',
                ],

                [
                    'log_statistic_id'        => '18',
                    'ip_address'               => '192.168.43.18',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/dosen',
                    'page_access'             => 'tentang-sttb/berita/dosen',
                    'hits_url_access'         => 6,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-08',
                ],

                [
                    'log_statistic_id'        => '19',
                    'ip_address'               => '192.168.43.19',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/paduan-suara-sttb',
                    'page_access'             => 'tentang-sttb/berita/paduan-suara-sttb',
                    'hits_url_access'         => 8,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-09',
                ],

                [
                    'log_statistic_id'        => '20',
                    'ip_address'               => '192.168.43.110',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/himatif',
                    'page_access'             => 'tentang-sttb/berita/himatif',
                    'hits_url_access'         => 10,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-10',
                ],

                [
                    'log_statistic_id'        => '21',
                    'ip_address'              => '192.168.43.111',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 7,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-04',
                ],

                [
                    'log_statistic_id'        => '22',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 11,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-05',
                ],

                [
                    'log_statistic_id'        => '23',
                    'ip_address'              => '192.168.43.113',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/lomba-di-dubai',
                    'page_access'             => 'tentang-sttb/berita/lomba-di-dubai',
                    'hits_url_access'         => 13,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-13',
                ],

                [
                    'log_statistic_id'        => '24',
                    'ip_address'              => '192.168.43.114',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/kerja-di-jepang',
                    'page_access'             => 'tentang-sttb/berita/kerja-di-jepang',
                    'hits_url_access'         => 7,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-14',
                ],

                [
                    'log_statistic_id'        => '25',
                    'ip_address'              => '192.168.43.115',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/dosen',
                    'page_access'             => 'tentang-sttb/berita/dosen',
                    'hits_url_access'         => 4,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-15',
                ],

                [
                    'log_statistic_id'        => '26',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 1,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-06',
                ],

                [
                    'log_statistic_id'        => '27',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 18,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-07',
                ],

                [
                    'log_statistic_id'        => '28',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 10,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-08',
                ],

                [
                    'log_statistic_id'        => '29',
                    'ip_address'              => '192.168.43.193',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 11,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-09',
                ],

                [
                    'log_statistic_id'        => '30',
                    'ip_address'              => '192.168.43.114',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 4,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-10',
                ],

                [
                    'log_statistic_id'        => '31',
                    'ip_address'              => '192.168.43.113',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 2,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2021-12-28',
                ],

                [
                    'log_statistic_id'        => '32',
                    'ip_address'              => '192.168.43.118',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 5,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2021-12-29',
                ],

                [
                    'log_statistic_id'        => '33',
                    'ip_address'              => '192.168.43.119',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 1,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2021-12-30',
                ],

                [
                    'log_statistic_id'        => '34',
                    'ip_address'              => '192.168.43.116',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 7,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2021-12-31',
                ],

                [
                    'log_statistic_id'        => '35',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 1,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-01',
                ],

                [
                    'log_statistic_id'        => '36',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-02',
                ],

                [
                    'log_statistic_id'        => '37',
                    'ip_address'              => '192.168.43.110',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 4,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-03',
                ],

                [
                    'log_statistic_id'        => '38',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 9,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-11',
                ],

                [
                    'log_statistic_id'        => '39',
                    'ip_address'              => '192.168.43.113',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 12,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-12',
                ],

                [
                    'log_statistic_id'        => '40',
                    'ip_address'              => '192.168.43.117',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows',
                    'created_at'              => '2022-01-13',
                ],

                [
                    'log_statistic_id'        => '41',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 20,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-14',
                ],

                [
                    'log_statistic_id'        => '42',
                    'ip_address'              => '192.168.43.113',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 2,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-15',
                ],

                [
                    'log_statistic_id'        => '43',
                    'ip_address'              => '192.168.43.143',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 67,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows',
                    'created_at'              => '2022-01-14',
                ],

                [
                    'log_statistic_id'        => '44',
                    'ip_address'              => '192.168.43.144',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 80,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-15',
                ],

                [
                    'log_statistic_id'        => '45',
                    'ip_address'              => '192.168.43.144',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 21,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-16',
                ],

                [
                    'log_statistic_id'        => '46',
                    'ip_address'              => '192.168.43.113',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 45,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-17',
                ],

                [
                    'log_statistic_id'        => '47',
                    'ip_address'              => '192.168.43.144',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 30,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-18',
                ],

                [
                    'log_statistic_id'        => '48',
                    'ip_address'              => '192.168.43.180',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-19',
                ],

                [
                    'log_statistic_id'        => '49',
                    'ip_address'              => '192.168.43.190',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 41,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-20',
                ],

                [
                    'log_statistic_id'        => '50',
                    'ip_address'              => '192.168.43.190',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 50,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-20',
                ],

                [
                    'log_statistic_id'        => '51',
                    'ip_address'              => '192.168.43.190',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 89,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-21',
                ],

                [
                    'log_statistic_id'        => '52',
                    'ip_address'              => '192.168.43.190',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 45,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-22',
                ],

                [
                    'log_statistic_id'        => '53',
                    'ip_address'              => '192.168.43.120',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-23',
                ],

                [
                    'log_statistic_id'        => '54',
                    'ip_address'              => '192.168.43.128',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 32,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-24',
                ],

                [
                    'log_statistic_id'        => '55',
                    'ip_address'              => '192.168.43.129',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 67,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-24',
                ],

                [
                    'log_statistic_id'        => '56',
                    'ip_address'              => '192.168.43.190',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 45,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-23',
                ],

                [
                    'log_statistic_id'        => '57',
                    'ip_address'              => '192.168.43.191',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'computer',
                    'operating_system_access' => 'windows 10',
                    'created_at'              => '2022-01-24',
                ],

                [
                    'log_statistic_id'        => '58',
                    'ip_address'              => '192.168.43.117',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/lomba-di-dubai',
                    'page_access'             => 'tentang-sttb/berita/lomba-di-dubai',
                    'hits_url_access'         => 20,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-23',
                ],

                [
                    'log_statistic_id'        => '59',
                    'ip_address'              => '192.168.43.112',
                    'url_access'              => 'fe.sttbandung.ac.id/tentang-sttb/berita/lomba-di-dubai',
                    'page_access'             => 'tentang-sttb/berita/lomba-di-dubai',
                    'hits_url_access'         => 30,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-23',
                ],

                [
                    'log_statistic_id'        => '60',
                    'ip_address'              => '192.168.43.132',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 65,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-25',
                ],

                [
                    'log_statistic_id'        => '61',
                    'ip_address'              => '192.168.43.134',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 45,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-25',
                ],

                [
                    'log_statistic_id'        => '62',
                    'ip_address'              => '192.168.43.182',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 89,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-26',
                ],

                [
                    'log_statistic_id'        => '63',
                    'ip_address'              => '192.168.43.104',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 12,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-26',
                ],

                [
                    'log_statistic_id'        => '64',
                    'ip_address'              => '192.168.43.13',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-26',
                ],

                [
                    'log_statistic_id'        => '65',
                    'ip_address'              => '192.168.43.14',
                    'url_access'              => 'fe.sttbandung.ac.id/galeri-wisuda',
                    'page_access'             => 'mahasiswa/galeri-wisuda',
                    'hits_url_access'         => 5,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-26',
                ],

                [
                    'log_statistic_id'        => '66',
                    'ip_address'              => '192.168.43.15',
                    'url_access'              => 'fe.sttbandung.ac.id/kerjasama',
                    'page_access'             => 'tentang-sttb/kerjasama',
                    'hits_url_access'         => 3,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-26',
                ],

                [
                    'log_statistic_id'        => '67',
                    'ip_address'              => '192.168.43.182',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 89,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-27',
                ],

                [
                    'log_statistic_id'        => '68',
                    'ip_address'              => '192.168.43.104',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 54,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-27',
                ],

                [
                    'log_statistic_id'        => '69',
                    'ip_address'              => '192.168.43.13',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-27',
                ],

                [
                    'log_statistic_id'        => '70',
                    'ip_address'              => '192.168.43.14',
                    'url_access'              => 'fe.sttbandung.ac.id/galeri-wisuda',
                    'page_access'             => 'mahasiswa/galeri-wisuda',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-27',
                ],

                [
                    'log_statistic_id'        => '71',
                    'ip_address'              => '192.168.43.15',
                    'url_access'              => 'fe.sttbandung.ac.id/kerjasama',
                    'page_access'             => 'tentang-sttb/kerjasama',
                    'hits_url_access'         => 65,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-27',
                ],

                [
                    'log_statistic_id'        => '72',
                    'ip_address'              => '192.168.43.182',
                    'url_access'              => 'fe.sttbandung.ac.id/berita',
                    'page_access'             => 'tentang-sttb/berita',
                    'hits_url_access'         => 89,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-28',
                ],

                [
                    'log_statistic_id'        => '73',
                    'ip_address'              => '192.168.43.104',
                    'url_access'              => 'fe.sttbandung.ac.id/daftar-sekarang',
                    'page_access'             => 'daftar-sekarang',
                    'hits_url_access'         => 54,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-28',
                ],

                [
                    'log_statistic_id'        => '74',
                    'ip_address'              => '192.168.43.13',
                    'url_access'              => 'fe.sttbandung.ac.id/prestasi',
                    'page_access'             => 'mahasiswa/prestasi',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-28',
                ],

                [
                    'log_statistic_id'        => '75',
                    'ip_address'              => '192.168.43.14',
                    'url_access'              => 'fe.sttbandung.ac.id/galeri-wisuda',
                    'page_access'             => 'mahasiswa/galeri-wisuda',
                    'hits_url_access'         => 23,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-28',
                ],

                [
                    'log_statistic_id'        => '76',
                    'ip_address'              => '192.168.43.15',
                    'url_access'              => 'fe.sttbandung.ac.id/kerjasama',
                    'page_access'             => 'tentang-sttb/kerjasama',
                    'hits_url_access'         => 65,
                    'browser_access'          => 'chrome',
                    'device_access'           => 'mobile',
                    'operating_system_access' => 'android',
                    'created_at'              => '2022-01-28',
                ],

            ]
        );
    }
}
